### ISSUE TITLE
Support Inverted Sections?

### ISSUE THREAD

**Issue by raradek** [fieldrndservices/labstache#2]
Hi, thank you for the great toolkit. I'm trying to use inverted section as they are described in moustache doc. Are they not supported or am i doing something wrong?

- from the doc:

> Inverted Sections
> An inverted section begins with a caret (hat) and ends with a slash. That is {{^person}} begins a "person" inverted section while {{/person}} ends it.
> 
> While sections can be used to render text one or more times based on the value of the key, inverted sections may render text once based on the inverse value of the key. That is, they will be rendered if the key doesn't exist, is false, or is an empty list.
> 
> Template:
> 
> {{#repo}}
>   <b>{{name}}</b>
> {{/repo}}
> {{^repo}}
>   No repos :(
> {{/repo}}
> Hash:
> 
> {
>   "repo": []
> }
> Output:
> 
> No repos :(

**Comment by volks73** [comment]
> Hi, thank you for the great toolkit. 

Your welcome! I am glad you are finding it useful.

> I'm trying to use inverted section as they are described in moustache doc. Are they not supported or am i doing something wrong?

Inverted sections should be supported. There is a functional test in the source code for the project that might be useful as a template/example. Please see [Render Inverted Section](https://github.com/fieldrndservices/labstache/blob/master/tests/Render/Render%20Inverted%20Section.vi) VI. I just ran this test/VI on my system and it passes. I admit, it is a very simple test and more tests could be helpful.

Does the "[Simple - String Input](https://github.com/fieldrndservices/labstache/blob/master/src/Examples/Simple%20-%20String%20Input.vi)" example VI work for you on your system with the template you are trying to use?

There is a chance there is a bug in the toolkit. Can you provide a VI snippet or some code that is not working for you?

**Comment by raradek** [comment]
.. i actually haven't described the issue quite correctly - the problem is that in some cases both sections   i.e.

` {{#section}}{{/section}}`

 and

` {{^section}}{{/section}}` 

are rendered:
I think the situation can be narrowed down to this:

![Inverted Section Labstache](https://user-images.githubusercontent.com/17134913/76455713-403b4a00-63d6-11ea-8cca-9938aa60aded.png)

**Comment by volks73** [comment]
Hmm. My initial guess is that this is a bug and related to the truthiness of the Array object/value. It looks like an array datum will always evaluate to `True` AND `False`...interesting. I am assuming the desired behavior is an empty array would print the `nok` case. I am not sure what the behavior should be if the array is not empty but only contains a `Null` element. I will have to investigate further when I get some more time later this week.

Thank you for the VI snippet. It is extremely useful as I can convert that into some nice functional tests.

As a simple workaround, you could check for the empty array in LabVIEW and pass a boolean to the section pair, then embed another section within the `ok` case for looping through the array. While this is not an elegant solution and nested sections can confusing, it should at least work in the near term.

**Comment by volks73** [comment]
I finally had a chance to look into this.

I was able to create some tests from your (@raradek) VI snippet and re-create the issue. The source of the problem was in the rendering of sections when the data was an Array. If the array was non-empty, then the rendering did not take into account whether the section was inverted or not. So, in your VI snippet, and the new tests, the parsers sees two section nodes, one non-inverted and one inverted. The inverted one was being treated as a non-inverted section when the data was an array. It had nothing to do with the truthiness as first suspected.

However, a small side note about truthiness. There is nothing in the Mustache specification about the truthiness of an array of nulls or an array with an empty value (Map). It only cares if the array has at least one element. In all cases from the VI snippet, and now tests, the array datum is _not_ empty, irregardless of the truthiness of the element's value. Thus, "ok" should be printed.

**Comment by volks73** [comment]
I believe I have resolved this issue as of 30a45639543592dd2fd3bb945ce4bfc0aab8008c.

I have already created a [new release, v1.1.1](https://github.com/fieldrndservices/labstache/releases/tag/1.1.1), that includes this resolution and I will submit to the NI Tools Network shortly.
